///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
// ignore_for_file: non_constant_identifier_names

class ConferenciaPedidoModel {
/*
{
  "DAT_PEDI": "13/09/2021",
  "COD_VEN": "00011",
  "COD_CLI": "00003",
  "VLR_TOTA": 54.25,
  "NUM_PEDI": 25,
  "LOCALVENDA": "",
  "NOM_CLI": "CONSUMIDOR",
  "COD_PROD": "47421",
  "QTD_PROD": 1,
  "DES_PROD": "PALHETA DIANT 22X20 LOGAN/SANDERO 14/..."
} 
*/

  String? DATPEDI;
  String? CODVEN;
  String? CODCLI;
  String? VLRTOTA;
  String? NUMPEDI;
  String? LOCALVENDA;
  String? NOMCLI;
  String? CODPROD;
  String? QTDPROD;
  String? DESPROD;

  ConferenciaPedidoModel({
    this.DATPEDI,
    this.CODVEN,
    this.CODCLI,
    this.VLRTOTA,
    this.NUMPEDI,
    this.LOCALVENDA,
    this.NOMCLI,
    this.CODPROD,
    this.QTDPROD,
    this.DESPROD,
  });
  
  ConferenciaPedidoModel.fromJson(Map<String?, dynamic> json) {
    DATPEDI = json['DAT_PEDI']?.toString();
    CODVEN = json['COD_VEN']?.toString();
    CODCLI = json['COD_CLI']?.toString();
    VLRTOTA = json['VLR_TOTA']?.toString();
    NUMPEDI = json['NUM_PEDI']?.toString();
    LOCALVENDA = json['LOCALVENDA']?.toString();
    NOMCLI = json['NOM_CLI']?.toString();
    CODPROD = json['COD_PROD']?.toString();
    QTDPROD = json['QTD_PROD']?.toString();
    DESPROD = json['DES_PROD']?.toString();
  }

  Map<String?, dynamic> toJson() {
    final data = <String, Object?>{};
    data['DAT_PEDI'] = DATPEDI;
    data['COD_VEN'] = CODVEN;
    data['COD_CLI'] = CODCLI;
    data['VLR_TOTA'] = VLRTOTA;
    data['NUM_PEDI'] = NUMPEDI;
    data['LOCALVENDA'] = LOCALVENDA;
    data['NOM_CLI'] = NOMCLI;
    data['COD_PROD'] = CODPROD;
    data['QTD_PROD'] = QTDPROD;
    data['DES_PROD'] = DESPROD;
    return data;
  }
}
